/**
 * generated by Xtext 2.36.0
 */
package fm.limboole.impl;

import fm.limboole.Iff;
import fm.limboole.LimboolePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Iff</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IffImpl extends ExprImpl implements Iff
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IffImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LimboolePackage.Literals.IFF;
  }

} //IffImpl
