/**
 * generated by Xtext 2.36.0
 */
package fm.limboole.impl;

import fm.limboole.Implies;
import fm.limboole.LimboolePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Implies</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ImpliesImpl extends ExprImpl implements Implies
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImpliesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LimboolePackage.Literals.IMPLIES;
  }

} //ImpliesImpl
