/*
 * generated by Xtext 2.36.0
 */
package fm.parser.antlr;

import com.google.inject.Inject;
import fm.parser.antlr.internal.InternalLimbooleParser;
import fm.services.LimbooleGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LimbooleParser extends AbstractAntlrParser {

	@Inject
	private LimbooleGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLimbooleParser createParser(XtextTokenStream stream) {
		return new InternalLimbooleParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Expr";
	}

	public LimbooleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LimbooleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
