/*
 * generated by Xtext 2.36.0
 */
package fm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LimbooleStandaloneSetup extends LimbooleStandaloneSetupGenerated {

	public static void doSetup() {
		new LimbooleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
