/*
 * generated by Xtext 2.36.0
 */
package fm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLimbooleScopeProvider extends DelegatingScopeProvider {
}
