/**
 * generated by Xtext 2.36.0
 */
package fm.limboole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fm.limboole.LimboolePackage#getAnd()
 * @model
 * @generated
 */
public interface And extends Expr
{
} // And
