/**
 * generated by Xtext 2.36.0
 */
package fm.limboole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Implies</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fm.limboole.LimboolePackage#getImplies()
 * @model
 * @generated
 */
public interface Implies extends Expr
{
} // Implies
